/*
 * File:        pa2Globals.c
 * Description: Define global variables to calculate the offsets of members
 *              within structs.
 *
 * XXX DO NOT EDIT THIS FILE
 *
 */

#include <time.h>
#include <stddef.h> /* for offsetof() MACRO */
#include "pa2.h"

/* The struct timeInfo gives calendar time. */
size_t timeInfo_hourOffset = offsetof( struct timeInfo, tm_hour );

size_t timeInfo_minOffset = offsetof( struct timeInfo, tm_min );

size_t timeInfo_secOffset = offsetof( struct timeInfo, tm_sec );

size_t timeInfo_ampmOffset = offsetof( struct timeInfo, am_pm );

/* Offsets into the struct tm */
size_t tm_hour_offset = offsetof( struct tm, tm_hour );

size_t tm_min_offset = offsetof( struct tm, tm_min );


size_t tm_sec_offset = offsetof( struct tm, tm_sec );
